on:
  schedule:
    - cron: "42 * * * *"  # Runs every hour at the 34th minute
  workflow_dispatch:

jobs:
  daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Print a daily message
        run: echo "Running the daily scheduled task!"
